[2023-12-26T07:03:48.469+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL.Data_Cleaning scheduled__2023-12-25T06:30:00+00:00 [queued]>
[2023-12-26T07:03:48.474+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL.Data_Cleaning scheduled__2023-12-25T06:30:00+00:00 [queued]>
[2023-12-26T07:03:48.474+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T07:03:48.474+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2023-12-26T07:03:48.474+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T07:03:48.482+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): Data_Cleaning> on 2023-12-25 06:30:00+00:00
[2023-12-26T07:03:48.494+0000] {standard_task_runner.py:52} INFO - Started process 1035 to run task
[2023-12-26T07:03:48.505+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'Data_Cleaning', 'scheduled__2023-12-25T06:30:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_saepul_hilal_DAG.py', '--cfg-path', '/tmp/tmp4imb14b6', '--error-file', '/tmp/tmpbqerja8g']
[2023-12-26T07:03:48.508+0000] {standard_task_runner.py:80} INFO - Job 69: Subtask Data_Cleaning
[2023-12-26T07:03:48.560+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL.Data_Cleaning scheduled__2023-12-25T06:30:00+00:00 [running]> on host 0df44d59871b
[2023-12-26T07:03:48.598+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=saepul
AIRFLOW_CTX_DAG_ID=ETL
AIRFLOW_CTX_TASK_ID=Data_Cleaning
AIRFLOW_CTX_EXECUTION_DATE=2023-12-25T06:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-25T06:30:00+00:00
[2023-12-26T07:03:48.704+0000] {python.py:173} INFO - Done. Returned value was: None
[2023-12-26T07:03:48.712+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=Data_Cleaning, execution_date=20231225T063000, start_date=20231226T070348, end_date=20231226T070348
[2023-12-26T07:03:48.725+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-26T07:03:48.814+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
